name: compile ingDIY LEDremote

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`

        echo '# setup for: LED Drums; PCB ver 2.63; variant "LED Drums" ver 2.60          ' >>platformio.ini
        echo '[env:LEDremote]                                                             ' >>platformio.ini
        echo 'extends = env:esp32dev                                                      ' >>platformio.ini
        echo 'build_flags = ${common.build_flags_esp32}                                   ' >>platformio.ini
        echo '  -D WLED_MAX_BUTTONS=1                                                     ' >>platformio.ini
        echo '  -D BTNPIN=-1                                                              ' >>platformio.ini
        echo '  -D DEFAULT_LED_COUNT=0                                                    ' >>platformio.ini
        echo '  -D DEFAULT_LED_TYPE=TYPE_NONE                                             ' >>platformio.ini
        echo '  -D WLED_ENABLE_INFRARED                                                   ' >>platformio.ini
        echo '  -D IRPIN=12                                                               ' >>platformio.ini
        echo '  -D IRTYPE=4                           # 4= 40-key RGB                     ' >>platformio.ini
        echo '  -D USERMOD_AUDIOREACTIVE                                                  ' >>platformio.ini
        echo '  -D UM_AUDIOREACTIVE_USE_NEW_FFT                                           ' >>platformio.ini
        echo '  -D SR_DMTYPE=1                        # 1=generic I2S (default)           ' >>platformio.ini
        echo '  -D I2S_CKPIN=17                                                           ' >>platformio.ini
        echo '  -D I2S_SDPIN=16                                                           ' >>platformio.ini
        echo '  -D I2S_WSPIN=4                                                            ' >>platformio.ini
        echo '  -D MCLK_PIN=-1                                                            ' >>platformio.ini
        echo '  -D USERMOD_AUTO_SAVE                                                      ' >>platformio.ini
        echo '  -D AUTOSAVE_AFTER_SEC=10                                                  ' >>platformio.ini
        echo '  -D USERMOD_AUTO_SAVE_ON_BOOT=true                                         ' >>platformio.ini
        echo '  -D HW_PIN_SCL=27                                                          ' >>platformio.ini
        echo '  -D HW_PIN_SDA=26                                                          ' >>platformio.ini
        echo '  -D USERMOD_FOUR_LINE_DISPLAY                                              ' >>platformio.ini
        echo '  -D USE_ALT_DISPlAY                                                        ' >>platformio.ini
        echo '  -D FLD_TYPE=SH1106                                                        ' >>platformio.ini
        echo '  -D USERMOD_ROTARY_ENCODER_UI                                              ' >>platformio.ini
        echo '  -D USERMOD_ROTARY_ENCODER_GPIO=INPUT                                      ' >>platformio.ini
        echo '  -D ENCODER_DT_PIN=21                                                      ' >>platformio.ini
        echo '  -D ENCODER_CLK_PIN=23                                                     ' >>platformio.ini
        echo '  -D ENCODER_SW_PIN=0                                                       ' >>platformio.ini
        echo '  -D WLED_AP_SSID_UNIQUE                                                    ' >>platformio.ini
        echo '  -D SERVERNAME="\"LEDremote\""                                             ' >>platformio.ini
        echo 'lib_deps = ${esp32.lib_deps}                                                ' >>platformio.ini
        echo '  https://github.com/kosme/arduinoFFT#develop @ 1.9.2                       ' >>platformio.ini
        echo '  U8g2                                  # For use SSD1306 OLED display      ' >>platformio.ini
        echo '  Wire                                  # For use SSD1306 OLED display      ' >>platformio.ini
        echo 'lib_ignore =                                                                ' >>platformio.ini
        echo '  ESPAsyncTCP                                                               ' >>platformio.ini
        echo '  ESPAsyncUDP                                                               ' >>platformio.ini
        pio run -e LEDremote || pio run -e LEDremote

    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/LEDremote.bin $GITHUB_WORKSPACE/_flashing/

    - name: Create utility files
      run: |
        cd $GITHUB_WORKSPACE
        echo '@echo off' >$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'echo Flashing LEDremote firmware...' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'esptool.py write_flash 0x10000 ./LEDremote.bin' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'echo.' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'echo Flashing done !!' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'timeout 5' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        echo 'exit' >>$GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat

        date '+%Y/%m/%d%t%T' >$GITHUB_WORKSPACE/_flashing/LEDremote_last_build_date.txt

    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/_flashing/LEDremote.bin
        git add $GITHUB_WORKSPACE/_flashing/LEDremote_flash.bat
        git add $GITHUB_WORKSPACE/_flashing/LEDremote_last_build_date.txt
        git commit -m "Commit Custom Build"
        git push origin develop
