name: compile ingDIY LEDdrums

on:
    workflow_dispatch:
    push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`

        echo '# setup for: LED Drums; PCB ver 4.20; variant "LED" ver 4.20                ' >>platformio.ini
        echo '[env:LEDdrums]                                                              ' >>platformio.ini
        echo 'extends = env:esp32dev                                                      ' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags}                                   ' >>platformio.ini
        echo '  -D WLED_MAX_BUTTONS=1                                                     ' >>platformio.ini
        echo '  -D BTNPIN=-1                                                              ' >>platformio.ini
        echo '  -D LEDPIN=16                                                              ' >>platformio.ini
        echo '  -D DEFAULT_LED_COUNT=50                                                   ' >>platformio.ini
        echo '  -D DEFAULT_LED_TYPE=TYPE_WS2812_RGB                                       ' >>platformio.ini
        echo '  -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB                                  ' >>platformio.ini
        echo '  -D ABL_MILLIAMPS_DEFAULT=1000                                             ' >>platformio.ini
        echo '  -D USERMOD_AUDIOREACTIVE                                                  ' >>platformio.ini
        echo '  -D UM_AUDIOREACTIVE_USE_NEW_FFT                                           ' >>platformio.ini
        echo '  -D SR_DMTYPE=4                        # 4=generic I2S with master clock   ' >>platformio.ini
        echo '  -D I2S_CKPIN=18                                                           ' >>platformio.ini
        echo '  -D I2S_SDPIN=5                                                            ' >>platformio.ini
        echo '  -D I2S_WSPIN=19                                                           ' >>platformio.ini
        echo '  -D MCLK_PIN=3                                                             ' >>platformio.ini
        echo '  -D I2S_USE_RIGHT_CHANNEL              # Use RIGHT instead of LEFT channel ' >>platformio.ini
        echo '  -D SR_SQUELCH=15                                                          ' >>platformio.ini
        echo '  -D SR_GAIN=30                                                             ' >>platformio.ini
        echo '  -D USERMOD_AUTO_SAVE                                                      ' >>platformio.ini
        echo '  -D AUTOSAVE_AFTER_SEC=10                                                  ' >>platformio.ini
        echo '  -D USERMOD_AUTO_SAVE_ON_BOOT=true                                         ' >>platformio.ini
        echo '  -D WLED_AP_SSID_UNIQUE                                                    ' >>platformio.ini
        echo '  -D CLIENT_SSID="\"StefPhone\""                                            ' >>platformio.ini
        echo '  -D SERVERNAME="\"LEDdrums\""                                              ' >>platformio.ini
        echo 'lib_deps = ${esp32.lib_deps}                                                ' >>platformio.ini
        echo '  https://github.com/kosme/arduinoFFT#develop @ 1.9.2                       ' >>platformio.ini
        pio run -e LEDdrums || pio run -e LEDdrums

    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/LEDdrums.bin $GITHUB_WORKSPACE/_flashing/

    - name: Create utility files
      run: |
        echo '@echo off' >$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'echo Flashing LEDdrums firmware...' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'esptool.py write_flash 0x10000 ./LEDdrums.bin' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'echo.' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'echo Flashing done !!' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'timeout 5' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        echo 'exit' >>$GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat

        date '+%Y/%m/%d%t%T' >$GITHUB_WORKSPACE/_flashing/LEDdrums_last_build_date.txt

    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/_flashing/LEDdrums.bin
        git add $GITHUB_WORKSPACE/_flashing/LEDdrums_flash.bat
        git add $GITHUB_WORKSPACE/_flashing/LEDdrums_last_build_date.txt
        git commit -m "Commit Custom Build"
        git push origin develop
